spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payments
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:/db/changelog-master.xml
